/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Powerboard                             */
/*      FILE         :  Powerboard.cpp                         */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <iodefine.h>
#include "board.h"
#include "gpio.h"
#include "e8504.h"

#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

int main(void) {

	init_board();
	e8504_testpattern();

    while(1) {
    	delay_ms(500);
    	LED1_Port = 1;
    	delay_ms(500);
    	LED1_Port = 0;
	// TODO: add application code here
    }
return 0;
}
